<h3 class="text-primary"> &nbsp; OMAHA Payment Procedure for Winter Session</h3>

<div class="row text-justify">
	
	<div class="col-xs-12 col-sm-9 col-md-12 col-lg-12">
		<p>	<i>	Last updated on Nov 30, 2014 14:00 IST</i></p>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			Read the instuctions carefully. It hardly takes two min.
		</div>
		<p>
			<strong>No DD’s or FDD will be accepted from any student.</strong> Institution is encouraging only on-line transfers. All students and parents are requested to co-operate.
		</p>
		<ol>
			<li>Hostel fee should not mix with Tuition Fee Payments.</li>
			<li>No Excess payments – No Refunds will be entertained from this time.</li>
			<li>Those who are paying Hostel Fee through NEFT/RTGS transfer (Except I-Collect/State Bank Collect) are advised to submit original payment/receipt in Hostel Office. It is mandatory to get fee endorsement from the Hostel Office before proceeding to Department for Registration. 
			</li>
		</ol>
		<hr>	
	</div>

	<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
		<strong>Category 1 : Education loan holders (NEFT transactions, Inter/Intra Bank Transfer to Chief Warden Account)</strong><br>
		<ul>
			<li>Make a single transaction for total amount</li>
			<li>
				Enter the transaction details on student portal using <strong class="text-info">WSDC Collect</strong>
				<ol>
					<li>
						Click an image of the transaction receipt and upload it.
						<ul>
							ENSURE THAT:
							<li>Transaction ID, amount paid and date is clearly visible.</li>
							<li>Receipt image is checked thoroughly before uploading.</li>
						</ul>
					</li>
					<li>Enter Transaction ID (NEFT transaction Reference Number/ Inter or Intra Bank Reference Number) and transaction date.</li>
				</ol>
			</li>					
			<li>
				Your transaction will be approved by Hostel Office within two working days (Mon-Fri)
				<ul>
					<li>Sometimes it might take 4-5 days to verify the transaction, please be patient.</li>
					<li>If transaction is not approved by Hostel Office, student should go to Hostel Office in person. No query will be entertained online.</li>
				</ul>
			</li>
			<li>Go to Hostel Office as soon as you reach college and submit the transaction receipt to <strong>Hostel Office, NIT Warangal</strong>
				<ul>
					<li>DD/NEFT receipt must be produced by student.</li>	
					<li><i>No Dues Certificate</i> will be issued by Hostel Office.</li>
					<!-- <li>Take two print out. of receipt generated by OMAHA (No dues certificate).</li> -->
					<li>Paste your recent passport size photo (coloured).</li>
					<li>
						Submit the no dues certificate to corresponding Mess.
						<ul>
							<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards<./li>
								<li>Old Mess boarders : Submit the no-dues certificate to respective mess.</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<p>	
				<a href="https://www.onlinesbh.com/prelogin/icollecthome.htm" class="btn btn-block btn-primary btn-md ">State Bank Collect</a>
			</p>
		</div>
	</div>
	<div class="row text-justify">
		<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
			<ul>
				<li>
					
					<strong>Category 2 : Payment via <a target="_blank" href="https://www.onlinesbh.com/prelogin/icollecthome.htm">i-collect or State Bank Collect</a></strong><br>
					<ul>
						<li>Enter all the details carefully on the portal, <span class="text-danger"> especially registration number and roll number.</span></li>
						<li>
							Your transaction will be uploaded by Hostel Office within two working days (Mon-Fri).
							<ul>
								<li>Sometimes it may take 4-5 days to verify and upload the transaction, please be patient.</li>
								<li>If transaction is not uploaded by Hostel Office, student should go to Hostel Office in person. No query will be entertained online.</li>
							</ul>
						</li>
						<li>Once the transaction is approved,</strong>
							<ul>
								<li>No need to go to hostel office.</li>
								<li>Take two print out of receipt generated by OMAHA (No dues certificate).</li>
								<li>Paste your recent passport size photo (coloured).</li>
								<li>
									Submit the no dues certificate to corresponding Mess.
									<ul>
										<li>For IFC A and IFC B boarders : Go to Ultra Mega Office for Mess cards.</li>
										<li>Old Mess boarders : Submit the no-dues certificate to respective mess.</li>
									</ul>
								</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<p>	
				<a href="<?php echo base_url('hostels/wsdc_collect/') ?> " class="btn btn-default btn-info btn-md btn-block">WSDC Collect <br> <small>for NEFT/Intra Bank</small></a>
			</p>
		</div>
	</div>
