<h3 class="text-primary"> &nbsp; OMAHA Payment Procedure for Winter Session</h3>

<div class="row text-justify">
	
	<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
		<p>	<i>	Last updated on Nov 30, 2014 14:00 IST</i></p>
		<div class="alert alert-danger">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			Read the instuctions carefully. It hardly takes two min.
		</div>
		<ul>
			<li>
				<strong>Category 1 : Education loan holders (DD/NEFT transactions, Inter/Intra Bank Transfer to Chief Warden Account)</strong><br>
				<ul>
					<li>Make a single transaction for mess dues, mess advance (INR 12,000)</li>
					<li>
						Enter the transaction details on student portal using <strong class="text-info">WSDC Collect</strong>
						<ul>
							<li>
								Take an image of the transaction receipt and upload
								<ul>
									<li>Transaction ID, amount paid and date should be clearly visible</li>
									<li>Receipt image should be checked thoroughly before uploading</li>
								</ul>
							</li>
							<li>Enter Transaction ID (DD Number/ NEFT transaction Reference Number/ Inter or Intra Bank Reference Number) and transaction date</li>
						</ul>
					</li>					
					<li>
						Your transaction will be approved by Hostel Office within two working days (Mon-Fri)
						<ul>
							<li>Sometimes it may take 4-5 weeks to verify the transaction, please be patience</li>
							<li>If transaction is not approved by Hostel Office, student should go to Hostel Office in person. No query will be entertained online</li>
						</ul>
					</li>
					<li>Go to Hostel Office as soon as you reach college and submit the transaction receipt to <strong>Hostel Office, NIT Warangal</strong>
						<ul>
							<li>You must produce the DD/NEFT receipt</li>	
							<li><i>No Dues Certificate</i> will be issued by Hostel Office</li>
							<!-- <li>Take two print out of receipt generated by OMAHA (No dues certificate).</li> -->
							<li>Past your recent passport size photo (coloured)</li>
							<li>
								Submit the no dues certificate to corresponding Messes
								<ul>
									<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards</li>
									<li>Old Mess boarders : Submit the no-dues certificate to respective mess</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>

			</li>	
		</ul>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">

		<p>	
			<a href="https://www.onlinesbh.com/prelogin/icollecthome.htm" class="btn btn-block btn-primary btn-md ">State Bank Collect <br>	  (Will start after exams)</a>
		</p>
	</div>
</div>
<div class="row text-justify">
	<div class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
		<ul>
			<li>
				<strong>Category 2 : Payment via <a target="_blank" href="https://www.onlinesbh.com/prelogin/icollecthome.htm">i-collect or State Bank Collect</a></strong><br>
				<ul>
					<li>Enter all the details carefully on the portal, <span class="text-danger"> especially registration number and roll number</span></li>
					<li>
						Your transaction will be uploaded by Hostel Office within two working days (Mon-Fri)
						<ul>
							<li>Sometimes it may take 4-5 weeks to verify and upload the transaction, please be patience</li>
							<li>If transaction is not uploaded by Hostel Office, student should go to Hostel Office in person. No query will be entertained online</li>
						</ul>
					</li>
					<li>Once the transaction is approved,
						<ul>
							<li>No need to go to hostel office</li>
							<li>Take two print out of receipt generated by OMAHA (No dues certificate).</li>
							<li>Past your recent passport size photo (coloured)</li>
							<li>
								Submit the no dues certificate to corresponding Messes
								<ul>
									<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards</li>
									<li>Old Mess boarders : Submit the no-dues certificate to respective mess</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>

			</li>

		</ul>
	</div>
	<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
		<p>	
			<a href="#" class="btn btn-primary btn-md btn-block">WSDC Collect <br>	 <small>for NEFT/DD/Intra Bank</small> <br>	 (Will start after exams)</a>
		</p>
	</div>
</div>

