<div class="well wsdc-well">
	<div class="container">
		<h1>Online Mess And Hostel Allotment (OMAHA) <small>Winter Session</small></h1>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="well">
			<p>State Bank Collect payment will start on 13th, Dec, 2014 (Tentative)</p>
			<a href="https://groups.google.com/forum/#!forum/omaha-winter">Click here for OMAHA Winter session Help Center</a>
		</div>
		
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<h3>Payment via RTGS/NEFT</h3>
			<p>Account Name: CHIEF WARDEN, NITW</p>

			<p>ACCOUNT NO: 52109375132</p>
			<p>IFSC code : SBHY0020149 ( within in INDIA)</p>

			<p>SWIFT code:  SBHYINBB018 (Transfer from abroad)</p>
		</div>

		<div class="col-xs-12 col-sm-6 col-md-9 col-lg-9">
			<h4 id="transacitonsummary">
				Transaction Summary of OMAHA
			</h4>
			<?php if (!empty($studenttransactions) && $studenttransactions != FALSE): ?>
				<table class="table table-hover table-condensed table-striped">
					<thead>
						<tr>
							<th>Reg No</th>
							<th>Mess dues</th>
							<th>Mess Advance</th>
							<th>Maintenance</th>
							<th>EMC </th>
							<th>Seat Rent</th>
							<th>Total</th>
							<th>Last update</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($studenttransactions as $key => $item): ?>
							<tr>
								<td><?php echo $item['regno'] ?></td>
								<td><?php echo $item['mess_dues'] ?></td>
								<td><?php echo $item['mess_advance'] ?></td>
								<td><?php echo $item['maintenance_charges'] ?></td>
								<td><?php echo $item['emc'] ?></td>
								<td><?php echo $item['seatrent'] ?></td>
								<td><?php echo $item['total'] ?></td>
								<td><?php echo $item['timestamp'] ?></td>
							</tr>
						<?php endforeach ?>
					</tbody>
				</table>
			<?php else: ?>
				<p class="text-danger">
					Your transaction is not listed here. Please go to Hostel Office, NITW and inform the same to the officials. Hostel Office must upload the information.
				</p>
			<?php endif; ?>
			<!-- payment procedure starts from here -->
			<h4>
				OMAHA Payment Procedure for Winter Session
			</h4>
			<p>
				<strong>No DD’s or FDD will be accepted from any student.</strong> Institution is encouraging only on-line transfers. All students and parents are requested to co-operate.
			</p>
			<ol>
				<li>Hostel fee should not mix with Tuition Fee Payments.</li>
				<li>No Excess payments – No Refunds will be entertained from this time.</li>
				<li>Those who are paying Hostel Fee through NEFT/RTGS transfer (Except I-Collect/State Bank Collect) are advised to submit original payment/receipt in Hostel Office. It is mandatory to get fee endorsement from the Hostel Office before proceeding to Department for Registration. 
				</li>
			</ol>

			<strong>Category 1 : Education loan holders (NEFT transactions, Inter/Intra Bank Transfer to Chief Warden Account)</strong><br>
			<ul>
				<li>Make a single transaction for mess dues, mess advance (INR 12,000).</li>
				<li>
					Enter the transaction details on student portal using <strong class="text-info">WSDC Collect</strong>
					<ol>
						<li>
							Click an image of the transaction receipt and upload it.
							<ul>
								ENSURE THAT:
								<li>Transaction ID, amount paid and date is clearly visible.</li>
								<li>Receipt image is checked thoroughly before uploading.</li>
							</ul>
						</li>
						<li>Enter Transaction ID (NEFT transaction Reference Number/ Inter or Intra Bank Reference Number) and transaction date.</li>
					</ol>
				</li>					
				<li>
					Your transaction will be approved by Hostel Office within two working days (Mon-Fri)
					<ul>
						<li>Sometimes it might take 4-5 days to verify the transaction, please be patient.</li>
						<li>If transaction is not approved by Hostel Office, student should go to Hostel Office in person. No query will be entertained online.</li>
					</ul>
				</li>
				<li>Go to Hostel Office as soon as you reach college and submit the transaction receipt to <strong>Hostel Office, NIT Warangal</strong>
					<ul>
						<li>DD/NEFT receipt must be produced by student.</li>	
						<li><i>No Dues Certificate</i> will be issued by Hostel Office.</li>
						<!-- <li>Take two print out. of receipt generated by OMAHA (No dues certificate).</li> -->
						<li>Paste your recent passport size photo (coloured).</li>
						<li>
							Submit the no dues certificate to corresponding Mess.
							<ul>
								<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards<./li>
									<li>Old Mess boarders : Submit the no-dues certificate to respective mess.</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>

				<br>
				<strong>Category 2 : Payment via <a target="_blank" href="https://www.onlinesbh.com/prelogin/icollecthome.htm">i-collect or State Bank Collect</a></strong><br>
				<ul>
					<li>Enter all the details carefully on the portal, <span class="text-danger"> especially registration number and roll number.</span></li>
					<li>
						Your transaction will be uploaded by Hostel Office within two working days (Mon-Fri).
						<ul>
							<li>Sometimes it may take 4-5 days to verify and upload the transaction, please be patient.</li>
							<li>If transaction is not uploaded by Hostel Office, student should go to Hostel Office in person. No query will be entertained online.</li>
						</ul>
					</li>
					<li>Once the transaction is approved,</strong>
						<ul>
							<li>No need to go to hostel office.</li>
							<li>Take two print out of receipt generated by OMAHA (No dues certificate).</li>
							<li>Paste your recent passport size photo (coloured).</li>
							<li>
								Submit the no dues certificate to corresponding Mess.
								<ul>
									<li>For IFC A and IFC B boarders : Go to Ultra Mega Office for Mess cards.</li>
									<li>Old Mess boarders : Submit the no-dues certificate to respective mess.</li>
								</ul>
							</li>
						</ul>
					</li>
				</ul>
				<hr>
			<!-- <p>State bank collect (i-collect) / DD / NEFT</p>
			<p>
				Students must pay following fees to avail Online Allotment
				<ul>
					<li>Mess Dues</li>
					<li>Mess Advance</li>
					<li>Maintenance Charges</li>
					<li>Seat Rent</li>
					<li>Water Elect.Charges</li>
				</ul>

				<strong>-To chief warden, NITW</strong>
			</p> -->
			<p class="text-primary">
				follow us on facebook for updates
				<div class="fb-like" data-href="https://www.facebook.com/wsdc.nitw" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
			</p>
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">

			<a href="<?php echo base_url('assets/downloads/omaha/winter/rules.pdf') ?>" class="btn btn-default btn-info btn-lg btn-block"> Download pdf<br> (Payment Procedure)<br> </a>
			<a href="https://www.onlinesbh.com/prelogin/icollecthome.htm" class="btn btn-default btn-info btn-lg btn-block">State Bank Collect <br> (Will start after exams)</a>
			<br>
			<!-- <a href="/student/hostels/wsdc_collect/" class="btn btn-default btn-info btn-lg btn-block">WSDC Collect <br> <small>for NEFT/DD/Intra Bank</small></a> -->
			<a href="#" class="btn btn-default btn-info btn-lg btn-block">WSDC Collect <br> <small>for NEFT/Intra Bank</small> <br> (Will start after exams)</a>
			<br>
			<p>You should pay following amount to Chief Warden, via i-collect (state bank collect) or NEFT/RTGS</p>
			<table class="table table-hover table-condensed table-striped">
				<thead>
					<tr>
						<th>Payment type</th>
						<th>Amount to be paid</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Mess dues</td>
						<!-- <td>&#x20B9; <?php echo $messdues ?> </td> -->
						<td>Will be uploading soon</td>
					</tr>
					<tr>
						<td>Mess Advance</td>
						<td>&#x20B9; 12000</td>
					</tr>
				</tbody>
			</table>
			<div class="well text-justify">
				Follow us on facebook and twitter for updates. <br>
				<a href="https://www.facebook.com/wsdc.nitw" target="_blank">facebook</a> | 
				<a href="https://www.twitter.com/wsdcnitw" target="_blank">twitter</a>
			</div>	
		</div>
	</div>
</div>
<div class="clearfix">
</div>
</div>

