<h3 class="text-primary">Online Mess And Hostel Allotment (OMAHA) <small>Winter Session</small></h3>
	<div class="row">
	<div class="well"><span class="glyphicon glyphicon-warning"></span> 	All 1st year student will be informed about the payment procedure on or before 8th Dec, 2014.</div>
		<div class="col-xs-12 col-sm-6 col-md-9 col-lg-9">
			<h4 id="transacitonsummary">
				Transaction Summary of OMAHA
			</h4>
			<?php if (!empty($studenttransactions) && $studenttransactions != FALSE): ?>
				<table class="table table-hover table-condensed table-striped">
					<thead>
						<tr>
							<th>Reg No</th>
							<th>Mess dues</th>
							<th>Mess Advance</th>
							<th>Maintenance</th>
							<th>EMC </th>
							<th>Seat Rent</th>
							<th>Total</th>
							<th>Last update</th>
						</tr>
					</thead>
					<tbody>
						<?php foreach ($studenttransactions as $key => $item): ?>
							<tr>
								<td><?php echo $item['regno'] ?></td>
								<td><?php echo $item['mess_dues'] ?></td>
								<td><?php echo $item['mess_advance'] ?></td>
								<td><?php echo $item['maintenance_charges'] ?></td>
								<td><?php echo $item['emc'] ?></td>
								<td><?php echo $item['seatrent'] ?></td>
								<td><?php echo $item['total'] ?></td>
								<td><?php echo $item['timestamp'] ?></td>
							</tr>
						<?php endforeach ?>
					</tbody>
				</table>
			<?php else: ?>
				<p class="text-danger">
					Your transaction is not listed here. Please go to Hostel Office, NITW and inform the same to the officials. Hostel Office must upload the information.
				</p>
			<?php endif; ?>
			<h4>
				OMAHA Payment Procedure for Winter Session
			</h4>
			<strong>Category 1 : Education loan holders (DD/NEFT transactions, Inter/Intra Bank Transfer to Chief Warden Account)</strong><br>
			<ul>
				<li>Make a single transaction for mess dues, mess advance (INR 12,000)</li>
				<li>
					Enter the transaction details on student portal using <strong class="text-info">WSDC Collect</strong>
					<ol>
						<li>
							Take an image of the transaction receipt and upload
							<ul>
								<li>Transaction ID, amount paid and date should be clearly visible</li>
								<li>Receipt image should be checked thoroughly before uploading</li>
							</ul>
						</li>
						<li>Enter Transaction ID (DD Number/ NEFT transaction Reference Number/ Inter or Intra Bank Reference Number) and transaction date</li>
					</ol>
				</li>					
				<li>
					Your transaction will be approved by Hostel Office within two working days (Mon-Fri)
					<ul>
						<li>Sometimes it may take 4-5 weeks to verify the transaction, please be patience</li>
						<li>If transaction is not approved by Hostel Office, student should go to Hostel Office in person. No query will be entertained online</li>
					</ul>
				</li>
				<li>Go to Hostel Office as soon as you reach college and submit the transaction receipt to <strong>Hostel Office, NIT Warangal</strong>
					<ul>
						<li>You must produce the DD/NEFT receipt</li>	
						<li><i>No Dues Certificate</i> will be issued by Hostel Office</li>
						<!-- <li>Take two print out of receipt generated by OMAHA (No dues certificate).</li> -->
						<li>Past your recent passport size photo (coloured)</li>
						<li>
							Submit the no dues certificate to corresponding Messes
							<ul>
								<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards</li>
								<li>Old Mess boarders : Submit the no-dues certificate to respective mess</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>

			<br>
			<strong>Category 2 : Payment via <a target="_blank" href="https://www.onlinesbh.com/prelogin/icollecthome.htm">i-collect or State Bank Collect</a></strong><br>
			<ul>
				<li>Enter all the details carefully on the portal, <span class="text-danger"> especially registration number and roll number</span></li>
				<li>
					Your transaction will be uploaded by Hostel Office within two working days (Mon-Fri)
					<ul>
						<li>Sometimes it may take 4-5 weeks to verify and upload the transaction, please be patience</li>
						<li>If transaction is not uploaded by Hostel Office, student should go to Hostel Office in person. No query will be entertained online</li>
					</ul>
				</li>
				<li>Once the transaction is approved,</strong>
					<ul>
						<li>No need to go to hostel office</li>
						<li>Take two print out of receipt generated by OMAHA (No dues certificate).</li>
						<li>Past your recent passport size photo (coloured)</li>
						<li>
							Submit the no dues certificate to corresponding Messes
							<ul>
								<li>For IFC A and IFC B boarders : Go to UltraMega Office for Mess cards</li>
								<li>Old Mess boarders : Submit the no-dues certificate to respective mess</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
			<hr>
			<!-- <p>State bank collect (i-collect) / DD / NEFT</p>
			<p>
				Students must pay following fees to avail Online Allotment
				<ul>
					<li>Mess Dues</li>
					<li>Mess Advance</li>
					<li>Maintenance Charges</li>
					<li>Seat Rent</li>
					<li>Water Elect.Charges</li>
				</ul>

				<strong>-To chief warden, NITW</strong>
			</p> -->
		</div>
		<div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
			<a href="https://www.onlinesbh.com/prelogin/icollecthome.htm" class="btn btn-default btn-info btn-lg btn-block">State Bank Collect <br> (Will start after exams)</a>
			<br>
			<!-- <a href="/student/hostels/wsdc_collect/" class="btn btn-default btn-info btn-lg btn-block">WSDC Collect <br> <small>for NEFT/DD/Intra Bank</small></a> -->
			<a href="#" class="btn btn-default btn-info btn-lg btn-block">WSDC Collect <br> <small>for NEFT/DD/Intra Bank</small> <br> (Will start after exams)</a>
			<br>
			<p>You should pay following amount to Chief Warden, via i-collect (state bank collect), DD or NEFT</p>
			<table class="table table-hover table-condensed table-striped">
				<thead>
					<tr>
						<th>Payment type</th>
						<th>Amount to be paid</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>Mess dues</td>
						<!-- <td>&#x20B9; <?php echo $messdues ?> </td> -->
						<td>Will be uploading soon</td>
					</tr>
					<tr>
						<td>Mess Advance</td>
						<td>&#x20B9; 12000</td>
					</tr>
				</tbody>
			</table>
			<div class="well text-justify">
				Follow us on facebook and twitter for updates. <br>
				<a href="https://www.facebook.com/wsdc.nitw" target="_blank">facebook</a> | 
				<a href="https://www.twitter.com/wsdcnitw" target="_blank">twitter</a>
			</div>	
		</div>
	</div>
</div>
<div class="clearfix">
</div>


